### ISSUE TITLE
Titre creation sondage

### ISSUE THREAD

**Issue by JacquesBonet** [collectivz/CollectivZ#72]
Le titre du sondage est mal formaté: 

Il apparait avec les tags html en clair.
![image](https://zube.io/files/pdecrat/e104b2dc5dd8f6d995297c42acb573fe.png)

**Comment by pdecrat** [comment]
Le bug devait venir de celui que tu avais temporairement introduit qui transformait tout les textes de message en lien. Je n'arrive pas à le reproduire, comportement correct.
